### PR TITLE
Use getSecret instead of getInput

### PR DESCRIPTION
**Pull request by LukasPukenis**
This hides the token from the logs

### CODE REVIEW

**Comment by ernestask** [comment]
Is it shown in the logs currently?

**Comment by ernestask** [comment]
```sh
➜  toolkit git:(main) git grep getSecret | wc -l
0
```

Where is that even defined?

**Comment by ernestask** [comment]
You can only do https://github.com/actions/toolkit/tree/main/packages/core#setting-a-secret. But, since the variables are already set as secrets in the projects, they are de-facto masked.

**Comment by LukasPukenis** [comment]
Thanks for pointing it out.

**Pull request closed without merging**
